created homework md, which explains the lessons learned in doing this…
cbfacademy/github-fundamentals-Sherelle-S pull request #2
Opened 2023-06-29 19:09 UTC by Sherelle-S

… homework, a summary of what i learend in the README.md, and what i still need to work on

2023-06-29 19:13 UTC, Sherelle-S commented
Hi Siobhan, 

I think this is what I was suppose to do, I missed the first link to the homework and thats where all the issues began. Fingers crossed, third time lucky!

If you could please take a look

2023-06-30 08:38 UTC, sohbaker reviewed
Hi Sherelle, 

This is a great start! I can see that you've experimened with a few different formatting options, which is good. 

A few comments: 

- You've mentioned that CBF would like you to apply GitHub to your work and how GitHub is best used for CBF. This task is about how GitHub is used in practice and getting you comfortable with the tools you'll need to use as a Software Developer
-

2023-06-30 08:57 UTC, sohbaker requested changes
Hi Sherelle,

This is a great start! I can see that you've experimented with a few different formatting options, which is good.
Feedback

1. You've mentioned that CBF would like you to apply GitHub to your work and how GitHub is best used for CBF. This learning is about how GitHub is used in practice and getting you comfortable with the tools you'll need to use as a Software Developer.

2. It would be great if you added a few examples of the commands, e.g. when you mention cloning a repository, what is the command for that?

3. For the code block quoting the homework task the syntax needs changing for it to format correctly. Check the code block example [here](https://markdownlivepreview.com/)

4. Be careful with your checkbox list at the end. The correct syntax is "- [ ]". Make sure that you have a space between the dash and the first square bracket and between the brackets themselves. If you wanted to update this later and mark a task as done, you would update it by putting an x in the middle "- [x]"

2023-07-04 19:04 UTC, sohbaker requested changes
This looks good!

Added a comment on the formatting of the checkboxes.

2023-07-04 19:04 UTC, sohbaker commented on homeword.md
> +- [] Find where the homework links are!!
Still need spaces here. To format checkboxes, this should be: 
`- [ ]`

2025-01-08 11:34 UTC, closed without merging